<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFsixwq3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFsixwq3/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFsixwq3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFsixwq3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFsixwq3\appProdProjectContainer(array(
    'container.build_hash' => 'Fsixwq3',
    'container.build_id' => '74557f16',
    'container.build_time' => 1536451461,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFsixwq3');
