<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKbes6ti\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKbes6ti/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKbes6ti.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKbes6ti\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKbes6ti\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Kbes6ti',
    'container.build_id' => '3ca0f89e',
    'container.build_time' => 1543258785,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKbes6ti');
