<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHsgxp3q\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHsgxp3q/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHsgxp3q.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHsgxp3q\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHsgxp3q\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Hsgxp3q',
    'container.build_id' => '1178e1c8',
    'container.build_time' => 1537813059,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHsgxp3q');
